### ISSUE TITLE
Interferring with captchas on other sites

### ISSUE THREAD

**Issue by karthikb351** [karthikb351/AutoCaptcha-for-IRCTC#3]
Issue on the Bescom site [here](https://www.bescom.co.in/SCP/MyAccount/QuickPayment.aspx)

![](https://pbs.twimg.com/media/CTmA_T0UEAAgtWT.png:large)

Reported [here](https://twitter.com/SriramVSharma/status/664704247733202944)

**Comment by karthikb351** [comment]
This makes no sense. Manifest doesn't give it permission to interfere with any other domain. :confused:

**Comment by kishore-narendran** [comment]
How do you know for certain this is messing things up?

**Comment by Deborah-Digges** [comment]
Looks OK to me
<img width="688" alt="screen shot 2015-11-13 at 10 45 11 am" src="https://cloud.githubusercontent.com/assets/3866405/11139303/a918390a-89f3-11e5-8704-df4e77a0dfed.png">

**Comment by kishore-narendran** [comment]
I think it doesn't work during non business hours :stuck_out_tongue: 
And, I tried it without the extension, still didn't work. So that's a problem with their captcha itself!
