### ISSUE TITLE
Doesn't work during tatkal

### ISSUE THREAD

**Issue by karthikb351** [karthikb351/AutoCaptcha-for-IRCTC#4]
IRCTC has a different, much harder, captcha during tatkal hours. :pensive:
#### Normal Hours

![](https://cloud.githubusercontent.com/assets/3104454/11452264/a687776c-9607-11e5-96b7-1484a8e8ef68.png)

---
#### Tatkal Hours

![](http://1.bp.blogspot.com/-km4SXvlftlg/VaNHbJCrVtI/AAAAAAAAAi8/oOdBGRze-JY/s1600/Screenshot%2B%252823%2529.png)

**Comment by karthikb351** [comment]
The catpcha URLs are the same, and IRCTC dynamically swaps them based on the time on the server, which means I'll need to wait till the next tatkal hour to download samples.

Looks like the Tatkal captcha is just multiple (lossless) overlays of single characters, each layer at a different angle/skew.

Possible fix: **One layer is always the upright text**, so we should be able to find that reliably.

Problem: It will be painstaking to generate masks from the images, since they now include lower letters too.

**Comment by sudhakar119** [comment]
hai, wonderful script,  but tatkal is most important , other rest of time no one get tension, there is no solution for u r  code, try it u will be success  for that also
