### ISSUE TITLE
Opening Credit links in new tab

### ISSUE THREAD

**Issue by palerdot** [karthikb351/AutoCaptcha-for-IRCTC#6]
I have created a pull request for this.
https://github.com/karthikb351/AutoCaptcha-for-IRCTC/pull/5

The problem with opening in the same page is, if someone clicks the credit links out of curiosity after typing all the information it will get lost. Making it opening in new tab will help retain the much needed typed information.

**Comment by karthikb351** [comment]
Agree 100%. Merged. Thanks for this!
